#!/bin/bash
echo Generating src/Makefile.am ...
inc_current='$(srcdir)'
inc_modules="$inc_current/modules"
inc_libraries="$inc_current/libraries"

cat > src/Makefile.am << EOF
AM_CPPFLAGS = -I$inc_current -I$inc_modules -I$inc_libraries -I$inc_libraries/enet/libenet/include \$(LOVE_INCLUDES) \$(FILE_OFFSET)
AM_CXXFLAGS = \$(SDL_CFLAGS)
AUTOMAKE_OPTIONS = subdir-objects
SUBDIRS =

if LOVE_BUILD_EXE
# LÖVE executable
bin_PROGRAMS = love
#love_LDFLAGS =
love_LDADD = liblove.la
love_SOURCES = love.cpp
endif

# Compile scripts
#scripts/%.lua.h: scripts/%.lua
#	cd scripts; \
#	lua auto.lua \$*
#TODO: Figure out how to only do this on gnu make, and detect which lua
#      executable to run

# libLÖVE
lib_LTLIBRARIES = liblove.la
liblove_la_LDFLAGS = -module -export-dynamic \$(LDFLAGS) \$(SDL_LIBS)
EOF

platform/unix/genmodules >> src/Makefile.am

printf "\n" >> src/Makefile.am

cd ..
echo "src/Makefile.am is updated! ^.^"
