.\" (c) 2008-2011 Miriam Ruiz <little_miry@yahoo.es>
.\"
.\" This software is provided 'as-is', without any express or implied warranty. In no event will the authors be held liable for any damagesarising from the use of this software.
.\"
.\" Permission is granted to anyone to use this software for any purpose, including commercial applications, and to alter it and redistribute it freely, subject to the following restrictions:
.\"
.\" 1. The origin of this software must not be misrepresented; you must not claim that you wrote the original software. If you use this software in a product, an acknowledgment in the product documentation would be appreciated but is not required.
.\"
.\" 2. Altered source versions must be plainly marked as such, and must not be misrepresented as being the original software.
.\"
.\" 3. This notice may not be removed or altered from any source distribution.
.\"
.\" Modifications:
.\" - Update version to 0.9 and remove reference to doc dir - Bart van Strien, 2013
.TH "LÖVE" "1" "0.9" "" ""
.SH "NAME"
love \- 2D game development framework
.SH "SYNOPSIS"
.B love
<\fIgame.love\fR>
.SH "DESCRIPTION"
LÖVE was created to be a user\-friendly engine in which simple (or complicated) games could be made without having extensive knowledge of system or graphics functions and without having to dedicate time towards developing the same engine features time and time again.
.P
Developed with cross\-platform implementation in mind, it utilizes the latest open source libraries to deliver a similar game experience, independent of operating system. By relying on the Lua scripting language for game\-specific programming, it allows even the novice game creator to quickly and efficiently develop an idea into a fully working game.
.SH "SEE ALSO"
You can find more information at \fIhttp://love2d.org/\fR
